// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLOeKpnDy_G5-BUTTBUWI4AfIDcrj38XQ',
    appId: '1:357685615536:web:your-web-app-id',
    messagingSenderId: '357685615536',
    projectId: 'evento-app-2ade7',
    authDomain: 'evento-app-2ade7.firebaseapp.com',
    storageBucket: 'evento-app-2ade7.firebasestorage.app',
    measurementId: 'G-XXXXXXXXXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG3YF0vSPj5x9ixImpxyaQuBnKHlDg61s',
    appId: '1:357685615536:android:b3c8e08ae864aedabfd475',
    messagingSenderId: '357685615536',
    projectId: 'evento-app-2ade7',
    storageBucket: 'evento-app-2ade7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLOeKpnDy_G5-BUTTBUWI4AfIDcrj38XQ',
    appId: '1:357685615536:ios:a119cb7f9c8d8d0abfd475',
    messagingSenderId: '357685615536',
    projectId: 'evento-app-2ade7',
    storageBucket: 'evento-app-2ade7.firebasestorage.app',
    iosBundleId: 'com.example.evento',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLOeKpnDy_G5-BUTTBUWI4AfIDcrj38XQ',
    appId: '1:357685615536:ios:a119cb7f9c8d8d0abfd475',
    messagingSenderId: '357685615536',
    projectId: 'evento-app-2ade7',
    storageBucket: 'evento-app-2ade7.firebasestorage.app',
    iosBundleId: 'com.example.evento',
  );
}
